# docker-compose up -d deluge
version: '2'
services:
  deluge:
    image: binhex/arch-deluge
    ports:
      - "8082:8082"
      - "58846:58846"
      - "58946:58946"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${HOME}/deluge/data:/data"
      - "${HOME}/deluge/config:/config"
    environment:
      PUID: 1000
      PGID: 1000
    restart: always
