# From the working directory of the app
# Note: Gems will be installed in `./vendor/bundle`
# docker-compose run --rm ruby <cmd>
#
# Examples:
# docker-compose run --rm ruby bundle install
# docker-compose run --rm ruby pry -Ilib
#
# For better support of signals (i.e., ctrl-C)
# docker-compose run --rm ruby bash -c "echo pid1 > /dev/null && irb $@"
# docker-compose run --rm ruby bash -c "echo pid1 > /dev/null && bundle $@"
# docker-compose run --rm ruby bash -c "echo pid1 > /dev/null && rake $@"
version: '2'
services:
  ruby:
    image: "ruby:latest"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}:/data"
    working_dir: "/data"
    environment:
      GEM_HOME: "/data/vendor/bundle"
      BUNDLE_PATH: "/data/vendor/bundle"
      BUNDLE_BIN: "/data/vendor/bundle/bin"
      BUNDLE_SILENCE_ROOT_WARNING: "1"
      BUNDLE_APP_CONFIG: "/data/vendor/bundle"
      PATH: "/data/vendor/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: "/tmp"
    user: "1000:1000"
